import { useState } from "react";
import { useNavigate } from "react-router-dom";
import QuestionCard from "../components/QuestionCard.jsx";
import FeedbackCard from "../components/FeedbackCard.jsx";
import { generateInterview, submitAnswer } from "../services/interviewService.js";

const JOB_ROLES = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Data Analyst",
  "Product Manager",
  "DevOps Engineer",
];

// Steps in the interview flow.
const STEP = {
  SELECT_ROLE: "SELECT_ROLE",
  ANSWERING: "ANSWERING",
  FEEDBACK: "FEEDBACK",
  DONE: "DONE",
};

export default function Interview() {
  const navigate = useNavigate();

  const [step, setStep] = useState(STEP.SELECT_ROLE);
  const [jobRole, setJobRole] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const [session, setSession] = useState(null); // { sessionId, questions }
  const [currentIndex, setCurrentIndex] = useState(0);
  const [submitting, setSubmitting] = useState(false);
  const [feedback, setFeedback] = useState(null);
  const [scores, setScores] = useState([]);

  async function handleStart(e) {
    e.preventDefault();
    if (!jobRole) return;
    setLoading(true);
    setError("");
    try {
      const resumeId = localStorage.getItem("preppilot_resume_id") || null;
      const data = await generateInterview({ jobRole, resumeId });
      setSession(data);
      setCurrentIndex(0);
      setScores([]);
      setStep(STEP.ANSWERING);
    } catch (err) {
      setError(
        err.response?.data?.message ||
          "Could not generate interview questions. Please try again."
      );
    } finally {
      setLoading(false);
    }
  }

  async function handleAnswerSubmit(answerText) {
    setSubmitting(true);
    setError("");
    try {
      const currentQuestion = session.questions[currentIndex];
      const result = await submitAnswer({
        sessionId: session.sessionId,
        questionId: currentQuestion.id,
        answerText,
      });
      setFeedback(result);
      setScores((prev) => [...prev, result.score ?? 0]);
      setStep(STEP.FEEDBACK);
    } catch (err) {
      setError(
        err.response?.data?.message || "Could not evaluate your answer. Please try again."
      );
    } finally {
      setSubmitting(false);
    }
  }

  function handleNext() {
    const isLast = currentIndex >= session.questions.length - 1;
    if (isLast) {
      setStep(STEP.DONE);
      return;
    }
    setCurrentIndex((prev) => prev + 1);
    setFeedback(null);
    setStep(STEP.ANSWERING);
  }

  const averageScore =
    scores.length > 0 ? (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(1) : "0.0";

  return (
    <div className="flex-1 px-4 py-16 flex flex-col items-center">
      <div className="w-full max-w-2xl">
        {step === STEP.SELECT_ROLE && (
          <>
            <h1 className="text-3xl font-bold text-slate-900 mb-2 text-center">
              Start a Mock Interview
            </h1>
            <p className="text-slate-500 text-center mb-8">
              Choose the role you're preparing for. Questions are generated by IBM Granite AI.
            </p>

            <form
              onSubmit={handleStart}
              className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm"
            >
              <label htmlFor="jobRole" className="block text-sm font-medium text-slate-700 mb-2">
                Job role
              </label>
              <select
                id="jobRole"
                value={jobRole}
                onChange={(e) => setJobRole(e.target.value)}
                className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 mb-4"
              >
                <option value="">Select a role...</option>
                {JOB_ROLES.map((role) => (
                  <option key={role} value={role}>
                    {role}
                  </option>
                ))}
              </select>

              {error && <p className="text-red-600 text-sm mb-4">{error}</p>}

              <button
                type="submit"
                disabled={!jobRole || loading}
                className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-60 disabled:cursor-not-allowed text-white font-medium rounded-md py-2 transition"
              >
                {loading ? "Generating questions..." : "Start Interview"}
              </button>
            </form>
          </>
        )}

        {step === STEP.ANSWERING && session && (
          <>
            {error && <p className="text-red-600 text-sm mb-4 text-center">{error}</p>}
            <QuestionCard
              question={session.questions[currentIndex]}
              index={currentIndex}
              total={session.questions.length}
              onSubmit={handleAnswerSubmit}
              submitting={submitting}
            />
          </>
        )}

        {step === STEP.FEEDBACK && feedback && (
          <FeedbackCard
            feedback={feedback}
            onNext={handleNext}
            isLastQuestion={currentIndex >= session.questions.length - 1}
          />
        )}

        {step === STEP.DONE && (
          <div className="bg-white border border-slate-200 rounded-xl p-8 text-center shadow-sm">
            <h2 className="text-2xl font-bold text-slate-900 mb-2">Interview Complete!</h2>
            <p className="text-slate-500 mb-4">
              You answered {session.questions.length} questions for {jobRole}.
            </p>
            <p className="text-4xl font-bold text-indigo-600 mb-6">{averageScore}/10</p>
            <div className="flex gap-3 justify-center">
              <button
                onClick={() => navigate("/history")}
                className="bg-slate-900 hover:bg-slate-800 text-white font-medium rounded-md px-5 py-2 transition"
              >
                View History
              </button>
              <button
                onClick={() => {
                  setStep(STEP.SELECT_ROLE);
                  setJobRole("");
                  setSession(null);
                }}
                className="bg-indigo-600 hover:bg-indigo-500 text-white font-medium rounded-md px-5 py-2 transition"
              >
                Start Another
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
